image: docker:latest

services:
  - docker:dind

stages:
  - build

sca-backend:
  stage: build
  script:
    - echo ${CI_PROJECT_DIR}
    - echo $(pwd)
    - ls -al
    - docker pull hysnsec/safety
    - docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
  artifacts:
    paths: [oast-results.json]
    when: always # What does this do?
  allow_failure: true #<--- allow the build to fail but don't mark it as such

